# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusion < Formula
  desc "Codify and deliver intentions to Kubernetes and Clouds"
  homepage "https://github.com/howieyuen/kusion"
  version "0.8.0-rc.0"
  license "Apache License"

  depends_on "kcl-lang/tap/kclvm"

  on_macos do
    url "https://github.com/howieyuen/kusion/releases/download/v0.8.0-rc.0/kusion_0.8.0-rc.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
    sha256 "f7966fc8e8d095a49036d8db95bf8d2b84144eecde10bba786d0baa9637ed7c7"

    def install
      bin.install "kusion"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kusion
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/howieyuen/kusion/releases/download/v0.8.0-rc.0/kusion_0.8.0-rc.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e075f8ae9d5cf409edf092911ce488593c8c1f081412b9ab8712061672176e53"

      def install
        bin.install "kusion"
      end
    end
  end

  test do
    system "#{bin}/kusion version"
  end
end
