# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusion < Formula
  desc "Codify and deliver intentions to Kubernetes and Clouds"
  homepage "https://github.com/howieyuen/kusion"
  version "0.7.6"
  license "Apache License"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/howieyuen/kusion/releases/download/v0.7.6/kusion_0.7.6_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "6263cdc391ebb18e62533eb59a0353673ae727c9f12111f99efe794f5582d3b9"

      def install
        bin.install "kusion"
      end
    end
  end

  test do
    system "#{bin}/kusion version"
  end
end
