# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusion < Formula
  desc "Codify and deliver intentions to Kubernetes and Clouds"
  homepage "https://github.com/howieyuen/kusion"
  version "0.7.5"
  license "Apache License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/howieyuen/kusion/releases/download/v0.7.5/kusion_0.7.5_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "303fb3e3590e5500a248b5b6287f5bfc5941b8d3fa5bbdb2c741e08740b5af38"

      def install
        bin.install "kusion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/howieyuen/kusion/releases/download/v0.7.5/kusion_0.7.5_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "825ca730a5babf16cc4885bc7ef2f9d4c7923bd8535689576b78523c7c41e785"

      def install
        bin.install "kusion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/howieyuen/kusion/releases/download/v0.7.5/kusion_0.7.5_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "4d188977d77992631ada9c330ff110559e44d5b39fb3c95dc16fca4405433707"

      def install
        bin.install "kusion"
      end
    end
  end

  test do
    system "#{bin}/kusion version"
  end
end
