# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusion < Formula
  desc "Codify and deliver intentions to Kubernetes and Clouds"
  homepage "https://github.com/howieyuen/kusion"
  version "0.7.3"
  license "Apache License"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/howieyuen/kusion/releases/download/v0.7.3/kusion_0.7.3_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "87f51761f2f667fa14b7559588d2f4f5dda67ac5acd06aab54d207b23370d968"

      def install
        bin.install "kusion"
      end
    end
  end

  test do
    system "#{bin}/kusion version"
  end
end
